services:
  frontend:
    build: .
    container_name: argentbank-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - frontend-node-modules:/app/node_modules

volumes : 
  frontend-node-modules: